# Generated by Django 2.2.7 on 2019-11-12 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_ticket_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='board',
            field=models.ForeignKey(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_tickets', to='book.Station'), on_delete=django.db.models.deletion.CASCADE, related_name='board_tickets', to='book.Station'),
        ),
    ]
