# Generated by Django 2.2.7 on 2019-11-13 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_ticket_board_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='board_schedule',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='board_schedule_tickets', to='book.Schedule'),
        ),
    ]
