# Generated by Django 2.2.7 on 2019-11-13 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0021_auto_20191113_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='board_schedule',
            field=models.ForeignKey(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_schedule_tickets', to='book.Schedule'), on_delete=django.db.models.deletion.CASCADE, related_name='board_schedule_tickets', to='book.Schedule'),
        ),
    ]
