# Generated by Django 2.2.7 on 2019-11-13 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0024_remove_ticket_board_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='board_schedule',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='board_schedule_tickets', to='book.Schedule'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_tickets', to='book.Station'),
        ),
    ]
